import { readdir, readFile, writeFile } from 'fs/promises';
import path from 'path';

/**
 * CLI to convert markdown like thoughts to typescript files.
 */
async function main() {
	const out = path.join(__dirname, '..', 'app', 'thought-list.ts');
	const dir = path.join(__dirname, '..', 'thoughts');

	const files = await readdir(dir);

	let content = '/// This file was automatically generated by running `bun ./scripts/thoughts.ts`\n';

	content += (
`export interface Thought {
	postedAt: string;
	slug: string;
	title: string;
	text: string[];
	externalLink?: string;
}\n\n`
	);

	let thoughtList = [];

	for (const name of files.sort().reverse()) {
		const raw = await readFile(path.join(dir, name), 'utf-8');

		// Consider the 1st line to be JSON data,
		// then an empty line, and then the content.
		const [rawMeta, _, ...rawText] = raw.trim().split('\n');
		const meta = JSON.parse(rawMeta);
		const text = rawText.join('\n').split('\n\n');

		thoughtList.push({ ...meta, text });
	}

	content += `export const thoughtList: Thought[] = ${JSON.stringify(thoughtList, null, 2)};\n`;

	await writeFile(out, content);

	console.log(`Generated ${out}`);
}

main().catch(error => {
	console.error(error);
	process.exit(1);
});

